### ISSUE TITLE
Connection to remote host was lost

### ISSUE THREAD

**Issue by haarts** [gerarddejong/heat-pump-telemetry-exporter#2]
When spinning up the program with `python3 main.py` after editing the `config.py` and doing a curl request on `localhost:8888/metrics` I get:

```
Exception occurred during processing of request from ('127.0.0.1', 57959)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/private/tmp/heat-pump-telemetry-exporter/main.py", line 77, in do_GET
    metricsResponseString = HeatPumpTelemetry.getMetrics(HeatPumpTelemetry)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/heat-pump-telemetry-exporter/main.py", line 31, in getMetrics
    contentResponseString = webSocketConnection.recv()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_core.py", line 362, in recv
    opcode, data = self.recv_data()
                   ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
----------------------------------------
```

I've verified that the IP of the pump is correct and I manually applied the patch in PR #1.

**Comment by haarts** [comment]
This happens when your pump is set to another language than English. The keys of the `metrics` dict need to line up precisely.
